/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as BoardRouteImport } from './routes/board'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as PProjectIdRouteImport } from './routes/p.$projectId'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1IndexRouteImport } from './routes/api/v1/index'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IndexRoute = ApiV1IndexRouteImport.update({
  id: '/api/v1/',
  path: '/api/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/board': typeof BoardRoute
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/team': typeof TeamRoute
  '/api/mcp': typeof ApiMcpRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/u/$handle': typeof UHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/': typeof ApiV1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/board': typeof BoardRoute
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/team': typeof TeamRoute
  '/api/mcp': typeof ApiMcpRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/u/$handle': typeof UHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1': typeof ApiV1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/board': typeof BoardRoute
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/team': typeof TeamRoute
  '/api/mcp': typeof ApiMcpRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/u/$handle': typeof UHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/': typeof ApiV1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/board'
    | '/connect'
    | '/login'
    | '/team'
    | '/api/mcp'
    | '/p/$projectId'
    | '/u/$handle'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/v1/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/board'
    | '/connect'
    | '/login'
    | '/team'
    | '/api/mcp'
    | '/p/$projectId'
    | '/u/$handle'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/v1'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/board'
    | '/connect'
    | '/login'
    | '/team'
    | '/api/mcp'
    | '/p/$projectId'
    | '/u/$handle'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/v1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  BoardRoute: typeof BoardRoute
  ConnectRoute: typeof ConnectRoute
  LoginRoute: typeof LoginRoute
  TeamRoute: typeof TeamRoute
  ApiMcpRoute: typeof ApiMcpRoute
  PProjectIdRoute: typeof PProjectIdRoute
  UHandleRoute: typeof UHandleRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiV1IndexRoute: typeof ApiV1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/': {
      id: '/api/v1/'
      path: '/api/v1'
      fullPath: '/api/v1/'
      preLoaderRoute: typeof ApiV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  BoardRoute: BoardRoute,
  ConnectRoute: ConnectRoute,
  LoginRoute: LoginRoute,
  TeamRoute: TeamRoute,
  ApiMcpRoute: ApiMcpRoute,
  PProjectIdRoute: PProjectIdRoute,
  UHandleRoute: UHandleRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiV1IndexRoute: ApiV1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
